package com.mx.ApiRestCinepolis.model;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/*CREATE TABLE PELICULAS(
ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,--se hace autoincremento
CLAVE VARCHAR2(50)NOT NULL UNIQUE,
NOMBRE VARCHAR2(100)NOT NULL UNIQUE,
GENERO VARCHAR2 (70)NOT NULL,
PRECIO NUMBER NOT NULL
);
*/

@Entity
@Table(name="PELICULAS")
@NoArgsConstructor //constructor vacio
@AllArgsConstructor // constructor con todos los parametros
@Data 
public class Peliculas {
	
	@Id//SE AGREGA PORQUE TODAS LAS TABLAS TIENEN UN IDENTIFICADOR UNICO
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	
	@Column(name="ID",columnDefinition="NUMBER",nullable=false)
	private Long idPelicula;
	
	@Column(name="CLAVE",columnDefinition="VARCHAR2(50)",nullable=false,unique=true)
	private String clave;
	
	@Column(name="NOMBRE",columnDefinition="VARCHAR2(100)",nullable=false,unique=true)
	private String nombre;
	
	@Column(name="GENERO",columnDefinition="VARCHAR2(70)",nullable=false)
	private String genero;
	
	@Column(name="PRECIO",columnDefinition="NUMBER",nullable=false)
	private Float precio;
	

}
